# Generated by Django 5.2.7 on 2025-11-18 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_commment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commment',
            new_name='Comment',
        ),
    ]
